[package]
name = "staking-miner-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = { version = "0.37.0", features = ["substrate-compat"] }
tokio = { version = "1.39", features = ["full"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
anyhow = "1.0.71"
clap = { version = "4.3.2", features = ["derive"] } 
features = "0.10.0"
derive = "1.0.0"
tracing = "0.1.37"
futures = "0.3.28"
once_cell = "1.18"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde = "1"
serde_json = "1"
hex = "0.4.3"
jsonrpsee = { version = "0.22.3", features = ["ws-client"] }
# polkadot-staking-miner = { git = "https://github.com/paritytech/polkadot-staking-miner" }

# prometheus
prometheus = "0.13"
hyper = { version = "0.14.25", features = ["server", "http1", "http2", "tcp"] }

# polkadot-sdk
frame-election-provider-support = "37.0.0"
frame-support = "37.0.0"
frame-system = "37.0.0"
pallet-election-provider-multi-phase = "36.0.0"
sp-npos-elections = "34.0.0"
sp-runtime = "39.0.0"
