[package]
name = "polkadot-staking-miner-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive", "env"] }
codec = { version = "3.0.0", package = "parity-scale-codec" }
oasgen =  { version = "0.22.0", features = ["axum", "swagger-ui"] }
refinery = { version = "0.8.14", features = ["tokio-postgres"] }
scale-info = "2.11"
serde = "1"
serde_json = "1"
subxt = { version = "0.37.0", features = ["substrate-compat", "unstable-reconnecting-rpc-client"] }
thiserror = "1.0.64"
tokio = { version = "1.40", features = ["sync", "macros", "rt-multi-thread", "signal"] }
tokio-postgres = { version = "0.7.12", features = ["with-serde_json-1"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.2.2"

# Web API
axum = { version = "0.7.7",default-features = false, features = ["json"] }

# polkadot-sdk
pallet-election-provider-multi-phase = "37.0.0"
sp-npos-elections = "34.0.0"