[package]
name = "polkadot-staking-miner-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.5.17", features = ["derive"] }
codec = { version = "3.0.0", package = "parity-scale-codec" }
scale-info = "2.11"
serde = "1"
serde_json = "1"
subxt = { version = "0.37.0", features = ["substrate-compat", "unstable-reconnecting-rpc-client"] }
thiserror = "1.0.30"
tokio = { version = "1.40", features = ["sync", "macros", "rt-multi-thread"] }
tokio-postgres = "0.7.11"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.2.2"

# Web API
actix-web = "4.9"

# polkadot-sdk
pallet-election-provider-multi-phase = "36.0.0"
sp-npos-elections = "34.0.0"