name: Publish Docker image description

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile.README.md'

jobs:
  publish_docker_description:
    runs-on: ubuntu-latest
    environment: master_and_tags
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: paritytech-actions/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: 'paritytech/polkadot-staking-miner-monitor'
          short-description: 'polkadot-staking-miner-monitor'
          readme-filepath: 'Dockerfile.README.md'